[2023-12-02T13:56:49.926+0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: compare_task_score.test_model manual__2023-12-02T10:49:19.288720+00:00 [queued]>
[2023-12-02T13:56:50.142+0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: compare_task_score.test_model manual__2023-12-02T10:49:19.288720+00:00 [queued]>
[2023-12-02T13:56:50.142+0300] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-02T13:56:50.190+0300] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): test_model> on 2023-12-02 10:49:19.288720+00:00
[2023-12-02T13:56:50.198+0300] {standard_task_runner.py:57} INFO - Started process 12793 to run task
[2023-12-02T13:56:50.216+0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'compare_task_score', 'test_model', 'manual__2023-12-02T10:49:19.288720+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/run_airflow.py', '--cfg-path', '/tmp/tmpepmfmhbu']
[2023-12-02T13:56:50.221+0300] {standard_task_runner.py:85} INFO - Job 58: Subtask test_model
[2023-12-02T13:56:50.431+0300] {task_command.py:416} INFO - Running <TaskInstance: compare_task_score.test_model manual__2023-12-02T10:49:19.288720+00:00 [running]> on host MLOPS-3-3.myguest.virtualbox.org
[2023-12-02T13:56:50.821+0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='compare_task_score' AIRFLOW_CTX_TASK_ID='test_model' AIRFLOW_CTX_EXECUTION_DATE='2023-12-02T10:49:19.288720+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-02T10:49:19.288720+00:00'
[2023-12-02T13:56:50.847+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-02T13:56:50.851+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/petr/project/scripts/test_model.py']
[2023-12-02T13:56:50.918+0300] {subprocess.py:86} INFO - Output:
[2023-12-02T13:56:51.070+0300] {subprocess.py:93} INFO -   File "/home/petr/project/scripts/test_model.py", line 37
[2023-12-02T13:56:51.077+0300] {subprocess.py:93} INFO -     results = list(zip(models,test_score)
[2023-12-02T13:56:51.078+0300] {subprocess.py:93} INFO -                    ^^^^^^^^^^^^^^^^^^^^^^
[2023-12-02T13:56:51.078+0300] {subprocess.py:93} INFO - SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2023-12-02T13:56:51.105+0300] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-02T13:56:51.251+0300] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/petr/project/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-02T13:56:51.280+0300] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=compare_task_score, task_id=test_model, execution_date=20231202T104919, start_date=20231202T105649, end_date=20231202T105651
[2023-12-02T13:56:51.382+0300] {standard_task_runner.py:104} ERROR - Failed to execute job 58 for task test_model (Bash command failed. The command returned a non-zero exit code 1.; 12793)
[2023-12-02T13:56:51.445+0300] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-02T13:56:51.615+0300] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
