[2023-11-08T21:51:56.273+0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_task_score.train_model manual__2023-11-08T18:50:44.563762+00:00 [queued]>
[2023-11-08T21:51:56.469+0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_task_score.train_model manual__2023-11-08T18:50:44.563762+00:00 [queued]>
[2023-11-08T21:51:56.470+0300] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-08T21:51:56.540+0300] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): train_model> on 2023-11-08 18:50:44.563762+00:00
[2023-11-08T21:51:56.579+0300] {standard_task_runner.py:57} INFO - Started process 5756 to run task
[2023-11-08T21:51:56.586+0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'my_task_score', 'train_model', 'manual__2023-11-08T18:50:44.563762+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/run_airflow.py', '--cfg-path', '/tmp/tmpxdgjpx_8']
[2023-11-08T21:51:56.588+0300] {standard_task_runner.py:85} INFO - Job 35: Subtask train_model
[2023-11-08T21:51:56.805+0300] {task_command.py:416} INFO - Running <TaskInstance: my_task_score.train_model manual__2023-11-08T18:50:44.563762+00:00 [running]> on host MLOPS-3-3.myguest.virtualbox.org
[2023-11-08T21:51:57.088+0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='my_task_score' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2023-11-08T18:50:44.563762+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-08T18:50:44.563762+00:00'
[2023-11-08T21:51:57.090+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-08T21:51:57.095+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/petr/project/scripts/train_model.py']
[2023-11-08T21:51:57.117+0300] {subprocess.py:86} INFO - Output:
[2023-11-08T21:52:00.141+0300] {subprocess.py:93} INFO - /home/petr/project/venv/lib/python3.10/site-packages/pydantic/_internal/_fields.py:128: UserWarning: Field "model_server_url" has conflict with protected namespace "model_".
[2023-11-08T21:52:00.142+0300] {subprocess.py:93} INFO - 
[2023-11-08T21:52:00.142+0300] {subprocess.py:93} INFO - You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
[2023-11-08T21:52:00.142+0300] {subprocess.py:93} INFO -   warnings.warn(
[2023-11-08T21:52:00.154+0300] {subprocess.py:93} INFO - /home/petr/project/venv/lib/python3.10/site-packages/pydantic/_internal/_config.py:317: UserWarning: Valid config keys have changed in V2:
[2023-11-08T21:52:00.154+0300] {subprocess.py:93} INFO - * 'schema_extra' has been renamed to 'json_schema_extra'
[2023-11-08T21:52:00.154+0300] {subprocess.py:93} INFO -   warnings.warn(message, UserWarning)
[2023-11-08T21:52:10.906+0300] {subprocess.py:93} INFO - Registered model 'stfc' already exists. Creating a new version of this model...
[2023-11-08T21:52:11.127+0300] {subprocess.py:93} INFO - 2023/11/08 21:52:11 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: stfc, version 7
[2023-11-08T21:52:11.128+0300] {subprocess.py:93} INFO - Created version '7' of model 'stfc'.
[2023-11-08T21:52:21.888+0300] {subprocess.py:97} INFO - Command exited with return code 0
[2023-11-08T21:52:22.252+0300] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=my_task_score, task_id=train_model, execution_date=20231108T185044, start_date=20231108T185156, end_date=20231108T185222
[2023-11-08T21:52:22.446+0300] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-08T21:52:22.632+0300] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
