[2023-12-02T13:58:37.302+0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: compare_task_score.get_data manual__2023-12-02T10:58:29.213605+00:00 [queued]>
[2023-12-02T13:58:37.364+0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: compare_task_score.get_data manual__2023-12-02T10:58:29.213605+00:00 [queued]>
[2023-12-02T13:58:37.365+0300] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-02T13:58:37.378+0300] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): get_data> on 2023-12-02 10:58:29.213605+00:00
[2023-12-02T13:58:37.381+0300] {standard_task_runner.py:57} INFO - Started process 13199 to run task
[2023-12-02T13:58:37.389+0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'compare_task_score', 'get_data', 'manual__2023-12-02T10:58:29.213605+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/run_airflow.py', '--cfg-path', '/tmp/tmpbhu2qa4c']
[2023-12-02T13:58:37.390+0300] {standard_task_runner.py:85} INFO - Job 59: Subtask get_data
[2023-12-02T13:58:37.473+0300] {task_command.py:416} INFO - Running <TaskInstance: compare_task_score.get_data manual__2023-12-02T10:58:29.213605+00:00 [running]> on host MLOPS-3-3.myguest.virtualbox.org
[2023-12-02T13:58:37.575+0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='compare_task_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-12-02T10:58:29.213605+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-02T10:58:29.213605+00:00'
[2023-12-02T13:58:37.577+0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-02T13:58:37.578+0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/petr/project/scripts/get_data.py']
[2023-12-02T13:58:37.592+0300] {subprocess.py:86} INFO - Output:
[2023-12-02T13:58:38.122+0300] {subprocess.py:93} INFO - WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
[2023-12-02T13:58:38.122+0300] {subprocess.py:93} INFO - Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
[2023-12-02T13:58:38.122+0300] {subprocess.py:93} INFO - To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
[2023-12-02T13:58:38.362+0300] {subprocess.py:93} INFO - Requirement already satisfied: PyGithub in /home/petr/project/venv/lib/python3.10/site-packages (2.1.1)
[2023-12-02T13:58:38.367+0300] {subprocess.py:93} INFO - Requirement already satisfied: typing-extensions>=4.0.0 in /home/petr/project/venv/lib/python3.10/site-packages (from PyGithub) (4.8.0)
[2023-12-02T13:58:38.368+0300] {subprocess.py:93} INFO - Requirement already satisfied: pyjwt[crypto]>=2.4.0 in /home/petr/project/venv/lib/python3.10/site-packages (from PyGithub) (2.8.0)
[2023-12-02T13:58:38.369+0300] {subprocess.py:93} INFO - Requirement already satisfied: Deprecated in /home/petr/project/venv/lib/python3.10/site-packages (from PyGithub) (1.2.14)
[2023-12-02T13:58:38.369+0300] {subprocess.py:93} INFO - Requirement already satisfied: pynacl>=1.4.0 in /home/petr/project/venv/lib/python3.10/site-packages (from PyGithub) (1.5.0)
[2023-12-02T13:58:38.370+0300] {subprocess.py:93} INFO - Requirement already satisfied: requests>=2.14.0 in /home/petr/project/venv/lib/python3.10/site-packages (from PyGithub) (2.31.0)
[2023-12-02T13:58:38.371+0300] {subprocess.py:93} INFO - Requirement already satisfied: urllib3>=1.26.0 in /home/petr/project/venv/lib/python3.10/site-packages (from PyGithub) (2.0.7)
[2023-12-02T13:58:38.371+0300] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil in /home/petr/project/venv/lib/python3.10/site-packages (from PyGithub) (2.8.2)
[2023-12-02T13:58:38.394+0300] {subprocess.py:93} INFO - Requirement already satisfied: cryptography>=3.4.0 in /home/petr/project/venv/lib/python3.10/site-packages (from pyjwt[crypto]>=2.4.0->PyGithub) (41.0.5)
[2023-12-02T13:58:38.399+0300] {subprocess.py:93} INFO - Requirement already satisfied: cffi>=1.4.1 in /home/petr/project/venv/lib/python3.10/site-packages (from pynacl>=1.4.0->PyGithub) (1.16.0)
[2023-12-02T13:58:38.405+0300] {subprocess.py:93} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/petr/project/venv/lib/python3.10/site-packages (from requests>=2.14.0->PyGithub) (2023.7.22)
[2023-12-02T13:58:38.406+0300] {subprocess.py:93} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/petr/project/venv/lib/python3.10/site-packages (from requests>=2.14.0->PyGithub) (2.1.1)
[2023-12-02T13:58:38.406+0300] {subprocess.py:93} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/petr/project/venv/lib/python3.10/site-packages (from requests>=2.14.0->PyGithub) (3.4)
[2023-12-02T13:58:38.427+0300] {subprocess.py:93} INFO - Requirement already satisfied: wrapt<2,>=1.10 in /home/petr/project/venv/lib/python3.10/site-packages (from Deprecated->PyGithub) (1.15.0)
[2023-12-02T13:58:38.429+0300] {subprocess.py:93} INFO - Requirement already satisfied: six>=1.5 in /home/petr/project/venv/lib/python3.10/site-packages (from python-dateutil->PyGithub) (1.16.0)
[2023-12-02T13:58:38.431+0300] {subprocess.py:93} INFO - Requirement already satisfied: pycparser in /home/petr/project/venv/lib/python3.10/site-packages (from cffi>=1.4.1->pynacl>=1.4.0->PyGithub) (2.21)
[2023-12-02T13:58:44.930+0300] {subprocess.py:97} INFO - Command exited with return code 0
[2023-12-02T13:58:44.995+0300] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=compare_task_score, task_id=get_data, execution_date=20231202T105829, start_date=20231202T105837, end_date=20231202T105844
[2023-12-02T13:58:45.031+0300] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-02T13:58:45.059+0300] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
